name: package_kit_starter_v1
description: Weblifestarter Kit Starter.
version: 1.0.0
homepage: "https://weblifestarter.com"

environment:
  # sdk: ">=2.17.6 <3.0.0"
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  intl:
  auto_route:
  loading_indicator:
  font_awesome_flutter:
  dropdown_button2:
  dio:
  flutter_html:
  html:
  webviewx:
  connectivity_plus:
  url_launcher:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
